### ISSUE TITLE
Paper link

### ISSUE THREAD

**Issue by LeMei** [NUSTM/SemEval-2024_ECAC#1]
Hi, this paper link is invalid. I am really interested in this work, can you share with me?

**Comment by ffcarina** [comment]
@LeMei  Sorry, SemEval has yet to release the official version of our task paper, which will likely be published after the workshop in July. I have submitted the paper to arXiv, and I will notify you once it is successfully published in a few days. Thank you for your attention to our work!

**Comment by LeMei** [comment]
Can you share the arXiv link with me? Thanks in advance.

**Comment by ffcarina** [comment]
@LeMei The arXiv paper has just been published. Here is the link: [2405.13049](https://arxiv.org/abs/2405.13049).
